language: node_js
sudo: false
node_js:
- '8'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: "YLlrpN1qdVmM+KE+sGIYs+KPpxeEp/QeqNRhxVP4jMAyB71UKjIXCviizxzMwXmJLUsAaPVfFCuVHU33XCiiS8FISc6/L+vkNm3B3QbklxRdbbPEBVbXA+LwMlFwZ7v9lUhIfhXwZP6ZLjYxAJXLuXVHhQHjBxaR3O66DxUR6ZqS7ic3hxkCQR8ZoJota/+UNo+DMPsj2RrembPyAsdpgEvUdu0UC92XC9NFpOp988xP5ph60DjZdIBncICotoijiev1j41ldME23KHleG0U0RyHr1bmAPVex7+EaHqi4ukgTmiGeVbxgnVX/3dbt5F6+ZjKWuakU7xD/Fx1wqE8Q0IGjdA6mVmMveLIA/M1BTmCwDfbHNATqJvoBMz/ga+Ut+YI44iQzrUr68TyvEwnvMd7f4wvL/PsvHFzhK0wwmw4AAByscyBLflfMU79DBmblz5va3J9SsmMERmNQr4tlN2cw1LRhOzdJHwyXUMllSOjqKSWumzE0AsJWR000OxFmIsLlAG2X/E8HpL8W/gkjnetUBV9mf8f1hnQ9NSn9u4pgB7jY9fhr8hwqROusZquyxiGiMfb95GCJxhwTBcra4KrM1pYdg37HvgiwOeYeeUzkuC4OzA9EnWbaDfjZzu/AijcnfpxmXG7YPsRcClcGBTjywuoY4uEaxr8BFFRW3k="
  on:
    tags: true
    repo: heiseonline/embetty-base
    node_js: '8'
env:
  global:
    secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
