language: node_js
sudo: false
node_js:
- '8'
- '10'
- '11'
- '12'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: npm
    email: mick@heise.de
    api_key:
      secure: MzCQ6naR1D0ToIvdJvO2kM/i7/f2xtGrhQMDoiIIfxDaptpxxF6ZHA0W47Gaeo7VBKeUOMKYMtqQRq/5NFjyYsezW/3c+Qvh0TMg9YhPechaiZnFuH4+fL1fKuQthBnO5DqDpeTDo0NPnLGXI0J3hEHFLLKPGPD8b3ciMjwPjFqxG/YTaYOgRV/FaKqbJXLqFF2Mb/fVtYbIAlVb0mFvZMIQogOGn2m4xVGTkMbkpaAcTd4nAwuhRaI2V/2tcSANO2klMRcMIjWS9R1m9s5LsSwlPPbLiUxQktKn6ADUdumf3nB6VPEY3QWS9A+NqVgZFdHKJIskRgOD7sxh8MgEfU70gdkoycLfvfpwELfUGwJiwxAhZM7MBZTaEcpZrFwWLCpv5dgatvHrID5qF6w1tqSJawkQYYGmo/m3gndpymzZKf7wpaxKCFd2qF1C/AMeT7jSMGvoXwXAv8UKA9nGmL6fnGqV0U3M0Ad+Xrcj6BDhF6z7zXGiWMV9evbrn6JKB3LdeXo7Fb4UyWUrrJ/eEpXcHdVhQFIVs6znA7sAzli89VuXfRntH0wvJfos0e4A4DZkTmOWYFIj6+TKYcHFwcu4jW0aW7D1sXFv+JUzLMdeuN5UFc4Y/m7SAdS9T0YeKAi16hEM6CuajC/He8cxv5Bmuxti2qZtRo/TmLNuJUA=
    on:
      tags: true
      repo: heiseonline/embetty-base
      node_js: '8'
  - provider: releases
    api_key:
      secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
    file:
    - "$BASE_NAME.zip"
    - "$BASE_NAME.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      repo: heiseonline/embetty-base
      node_js: '8'
env:
  global:
  - BASE_NAME=embetty-base-$TRAVIS_TAG
