language: node_js
sudo: false
node_js:
- '8'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: "bZ479tRJdz0SFvrZoAsEmZ7R7VgJ4gDLG5UR/8ooRi5BkMS2NqeNhF6UB0k5MrfQwZgz7JmkobeVwnV4rH9y4B0MfFzO4zYbSxTln1CMzXFi2+kqHzPJImXwVCalPRMA6Gqdsgp8CNH/WhTOwNCj9vqR8Bid8B8XR1aoi3ZtU5zFvkBWrUcgjQsAJCnloaKsmUbjr4qDd28Mj+b/UxAkgQSnXQ36VVR6AI842u/mwaGDzRvqLF8oVsBSNqG15oEGoyb2K9YIpRyHucW9/KPXsUdXwmslL9RQveSgjRwphbHx5lduWtioRpDrWczoFSNVb+eGWKYQ4lkrWQ27+6soC/Ns6nKFYMQ5W0FGNIKAZz6xqonApUwcTFXm8+9aBH5qR8TMuN3CURN3LSiMnAm8C0N993wvASC7CKrdf3eDWWNsy+xbO19YXmHW3tK5jf9nFV7x6+Nf8VHilq36mUbtBRwAT/Q/+0pYPGxpdqdcNP/3ykefe1drWGasxd/571pJC6e6FFELc/enjD5N47Txuuh2eBdsBNPWBMrvF0nqR9TGiQqxDjaU3ScsSughirmbdZhZHVqzlBm+HF5HQhaD9cCgnnuOvBYEQjbTCfIoBEAcUqGhXRXkV8tCyihdEnD2UM4V9YXzI6/ArGbRNURAOzkoXDUrbc5GXtrTbpMYwBc="
  on:
    tags: true
    repo: heiseonline/embetty-base
    node_js: '8'
env:
  global:
    secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
